### ISSUE TITLE
Cannot edit blog posts

### ISSUE THREAD

**Issue by vicnevicne** [darknao/docker-dotclear#5]
I installed the latest Docker image (2.14.3) on a Synology NAS and successfully configured Dotclear on a MariaDB 5 running on the NAS. 
I can see the default blog post and navigate the admin UI, but as soon as I try to edit that post (or the default comment, or the default page), I'm getting a "This entry does not exist" error message.
I opened a discussion (in French) on the Dotclear forum - https://forum.dotclear.org/viewtopic.php?pid=343969#p343969 - and with the help of a fellow member, could track down the issue to a mixup in the $_REQUEST variable, where the "id" url parameter gets overwritten by the "id" cookie, ending up in no match from the DB of course.
Any idea of the cause ?
(if you don't speak French, I can translate and copy here more information from the forum post, just tell me)

**Comment by darknao** [comment]
Bonjour,
J'ai refait à l'instant une installation from scratch pour tester et je n'ai pas pu reproduire ce problème.
Quelle variante (ou tag) de l'image avez vous utilisé ? apache ou fpm ? Et utilisez vous un reverse proxy en amont ?

**Comment by vicnevicne** [comment]
Hello. Merci pour le suivi rapide !
C’est la version apache 2.14.3 linkée depuis la homepage du projet. Pas de reverse proxy, j’ai juste configuré le container pour rediriger le port 8880 du synology vers le port 80 de l’apache de dotclear (car le port 80 du NAS est déjà occupé).
C’est peut-être lié à l’implementation Docker du Synology, mais bon, c’est bizarre...

**Comment by darknao** [comment]
J'ai refait quelques tests, et toujours pas de problème en vue.
Par contre j'ai regardé les info dans mon cookie dotclear, et je n’ai qu'un seul paramètre dcxd dedans.
Pas de id, smid, ou stay_login, comme vous.
En cherchant plus loin, je constate que si je regarde sur mon interface Synology (qui est sur une toute autre adresse), j'ai effectivement un cookie avec les paramètres id, smid et stay_login.
J'en déduis donc qu'en utilisant le docker sur votre Synology, vous vous retrouvez avec le meme cookie, partagé entre le votre session Synology et celle de DotClear.
Pour confirmer, vous pouvez forcer une déconnexion de l'interface d'admin du syno (ce qui supprime le cookie id) et accéder à l'interface d'admin dotclear pour tenter de modifier un post.

**Comment by darknao** [comment]
J'ai relancé un build de l'image incluant l'activation de la conf php taggé production.

La conf par défaut ne configure pas la variable **request_order**, qui utilise donc le paramétrage de **variables_order**, qui est à **GPCS** et intègre les cookies.
La conf taggé production configure request_order à GP (pas de cookie) et devrait donc corrigé votre problème.
C'est de plus une bonne pratique, donc merci d'avoir remonté ce problème :+1: 

J'en ai profité pour intégrer la dernière version de dotclear 2.15.3.
La nouvelle version de l'image devrait être disponible sur docker hub dans une petite heure.

N'hésitez pas à rouvrir ce ticket si le problème est toujours présent après la mise à jour.

**Comment by vicnevicne** [comment]
Wow super.
Bien vu, le fait que le cookie "id" venait du DSM de Synology, je n'y avais pas pensé. Tout s'explique (y compris le fait que ça a fonctionné un moment - je n'avais pas encore lancé le DSM à cet instant).
Pour faire simple sur mon installation, j'ai juste recopié php.ini-production en php.ini sur mon image existante et ça fonctionne nickel.
Merci :-)
