### ISSUE TITLE
Mise à jours de Dotclear

### ISSUE THREAD

**Issue by Antoine2tt** [darknao/docker-dotclear#6]
Hello !

Je me permet d'ouvrir un ticket en français, 

Est-il possible de mettre à jour Dotclear en 2.18 ?

Merci beaucoup, et bonne fêtes !

**Comment by darknao** [comment]
Bonjour !
Aucun probleme, l'image 2.18 est en cours de build et devrait etre disponible dans quelques minutes sur le hub.

**Comment by Antoine2tt** [comment]
Merci beaucoup !! ^^
